version: '2.1'

services:

  node:
    image: node:latest
    volumes:
    - .:/code
    entrypoint:
    - /usr/bin/tail 
    - -f 
    - /etc/hosts

  gw:
    build: express-gateway
    expose:
      - 8080
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8080/ip -Hhost:hb.example.com || exit 1"]
      interval: 5s
      retries: 10
    # entrypoint: - /usr/bin/tail - -f - /etc/hosts
